n_epochs: 200
disable_pbar: False
callbacks: 
- name: csv

data:
  directory: models
  experiment: wse2_example
  train_data_path:
    - ./training_data
  val_data_path:
    - ./validation_data
  n_train: 1
  n_valid: 1
  bond_fraction: 1.0
  sampling_alpha: 0.0
  atoms_pad_multiple: 50
  nl_pad_multiple: 100
  batch_size: 1
  valid_batch_size: 1
  shuffle_buffer_size: 100
  energy_unit: eV
  pos_unit: Ang

model:
  atom_centered:
    descriptor:
      descriptor_name: ShallowTDSAAtomCenteredDescriptor
      use_fused_tensor: True
      num_tensordenses: 1
      max_tensordense_degree: 4
      num_tensordense_features: 12
      mp_steps: 0
      mp_degree: 4
      mp_options:
        num_heads: 4
        qkv_features: 32
      mp_basis_options:
        cutoff_fn: smooth_cutoff
        radial_fn: basic_fourier
        radial_kwargs: {}
        max_degree: 2
        num: 8
    radial_basis:
      cutoff: 8.0
      num_radial: 24
      max_degree: 4
      num_elemental_embedding: 32
  bond_centered:
    cutoff: 8.0
    max_basis_degree: 4
    max_degree: 4
    tensor_module: fused_tensor
    tensor_module_dtype: float32
    bond_expansion_options:
      cutoff_fn: smooth_cutoff
      radial_fn: basic_fourier
      radial_kwargs: {}
      max_degree: 4
      num: 24
  mlp:
    mlp_layer_widths: [32,16,32]
    mlp_dtype: float32
    mlp_activation_function: bent_identity

optimizer:
  lr: 0.005
  name: adan
  opt_kwargs:
    weight_decay: 0.001
  schedule:
    name: reduce_on_plateau
    factor: 0.9
    patience: 50
    min_scale: 0.01
    rtol: 0.01
    atol: 0
    cooldown: 25
    accumulation_size: 1

loss:
  name: weighted_mse_and_rmse
  loss_parameters:
    off_diagonal_weight: 4.0
    on_diagonal_weight : 1.0
    mse_weight         : 1.0
    rmse_weight        : 1.0
    loss_multiplier    : 5.0

patience: null
seed: 2465
