direction: right
vars: {
  d2-config: {
    layout-engine: elk
    # theme-id: 200
    pad: 40
  }
}

z: {
  label: ""
  equation: |latex
    \huge{Z}
  |
  class: input
}
r: {label: ""
    equation: |latex
        \huge{\mathbf{r}_{ij}}
    |
    class: input
}

sarb: Species-Aware\nRadial Basis {class: sarb}
ac: Atom\nCentered {class: ac}
bc: Bond\nCentered {class: bc}
rd: Residual\nDense {class: rd}
ondro: On-diagonal\nTensorDense\nReadout {class: ro}
offdro: Off-diagonal\nTensorDense\nReadout {class: ro}
onscsh: On-diagonal\nScale Shift {class: scaleshift}
offscsh: Off-diagonal\nScale Shift {class: scaleshift}
outs: H Irreps. {class: outs}

ac -> rd: {style: {stroke: "#000000"}}
z -> sarb -> ac -> bc -> rd: {style: {stroke: "#000000"}}
r -> sarb: {style: {stroke: "#000000"}}
r -> bc: {style: {stroke: "#000000"}}
rd -> ondro -> onscsh -> outs: {style: {stroke: "#000000"}}
rd -> offdro -> offscsh -> outs: {style: {stroke: "#000000"}}

classes: {
  empty: {
    label: ""
    width: 50
    height: 50
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  sarb: {
    style: {
      fill: "#44BB99"
      stroke: "#000000"
      font-size: 24
    }
  }
  ac: {
    style: {
      fill: "#BBCC33"
      stroke: "#000000"
      font-size: 24
    }
  }
  bc: {
    style: {
      fill: "#EEDD88"
      stroke: "#000000"
      font-size: 24
    }
  }
  rd: {
    style: {
      fill: "#EE8866"
      stroke: "#000000"
      font-size: 24
    }
  }
  ro: {
    style: {
      fill: "#FFAABB"
      stroke: "#000000"
      font-size: 24
    }
  }
  scaleshift: {
    style: {
      fill: "#77AADD"
      stroke: "#000000"
      font-size: 24
    }
  }
  outs: {
    style: {
      fill: "#DDDDDD"
      stroke: "#000000"
      multiple: true
      font-size: 24
    }
    shape: parallelogram
  }
  input: {
    width: 50
    height: 50
    shape: parallelogram
    style: {
      fill: "#99DDFF"
      stroke: "#000000"
      multiple: true
    }
  }
}
