vars: {
  d2-config: {
    layout-engine: elk
    # theme-id: 200
    pad: 10
  }
}

# ins: {equation: |latex 
#         Z_i, Z_j, r_{ij}|
# }
ins: {
  label: ""
  equation: |latex
    \large{Z,\ \mathbf{r}}
  |
  class: input
}
# ins.class: input
sarb: Species-Aware Radial Basis {class: sarb}
ac: Atom-Centered {class: ac}
bc: Bond-Centered {class: bc}
rd: Residual Dense {class: rd}
ondro: On-diagonal \nTensorDense Readout {class: ro}
offdro: Off-diagonal \nTensorDense Readout {class: ro}
outs: H Irreps. {class: outs}
# sarb.class: sarb

ac -> rd: {style: {stroke: "#000000"}}
ins -> sarb -> ac -> bc -> rd: {style: {stroke: "#000000"}}
rd -> ondro -> outs: {style: {stroke: "#000000"}}
rd -> offdro -> outs: {style: {stroke: "#000000"}}
# sarb -> ac: {style: {stroke: "#000000"}}
# ac -> bc: {style: {stroke: "#000000"}}
# bc -> rd

classes: {
  empty: {
    label: ""
    width: 50
    height: 50
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  sarb: {
    style: {
      fill: "#44BB99"
      stroke: "#000000"
    }
  }
  ac: {
    style: {
      fill: "#BBCC33"
      stroke: "#000000"
    }
  }
  bc: {
    style: {
      fill: "#EEDD88"
      stroke: "#000000"
    }
  }
  rd: {
    style: {
      fill: "#EE8866"
      stroke: "#000000"
    }
  }
  ro: {
    style: {
      fill: "#FFAABB"
      stroke: "#000000"
    }
  }
  outs: {
    style: {
      fill: "#DDDDDD"
      stroke: "#000000"
      multiple: true
    }
  }
  input: {
    # label: ""
    width: 50
    height: 50
    style: {
      fill: "#99DDFF"
      stroke: "#000000"
      multiple: true
    }
  }
}

# if colorset == 'light':
#     cset = namedtuple('Lcset',
#                     'light_blue orange    light_yellow pink    light_cyan 
#                      mint      pear       olive      pale_grey black')
#         return cset('#77AADD', '#EE8866', '#EEDD88', '#FFAABB', '#99DDFF',
#                     '#44BB99', '#BBCC33', '#AAAA00', '#DDDDDD', '#000000')

# if colorset == 'bright':
#         cset = namedtuple('Bcset',
#                     'blue      red        green      yellow     cyan
#                     purple     grey       black')
#         return cset('#4477AA', '#EE6677', '#228833', '#CCBB44', '#66CCEE',
#                     '#AA3377', '#BBBBBB', '#000000')
