# direction: right

# zi: Zi {class: empty}
# zj: Zj {class: empty}
# sarb_emb: Embedding (from Species-\nAware Radial Basis) {class: empty;label.near: top-center}
# f: "2-body features \{f\}" {class: empty;}#label.near: outside-top-center}
f: {label: ""
    equation: |latex
        \huge{\mathbf{x}^{2\mathrm{B}}_{ij}}
    |
    class: empty
    label.near: outside-bottom-center
}
# acf: "Atom-centered features \{F\}" {class: empty; label.near: outside-top-center}
acf: {
    label: ""
    class: empty
    equation: |latex
        \huge{\mathbf{x}^{\mathrm{AC}}}
    |
}

ac: Atom-Centered Descriptor {
    class: ac
    _.f.equation -> sum_j: {style: {stroke: "#000000"; font-color: black}}
    sum_j: ∑ j {class: operator}
    sum_j -> 3b: {style: {stroke: "#000000"; font-color: black}}
    3b: TensorDense {class: in_module}
    5b: TensorDense {class: in_module}
    3b -> 5b: {style: {stroke: "#000000"; font-color: black}}
    c: Concatenate  {class: in_module}
    sum_j  -> c: {style: {stroke: "#000000"; font-color: black}}
    3b -> c: {style: {stroke: "#000000"; font-color: black}}
    5b -> c: {style: {stroke: "#000000"; font-color: black}}
    # transformed_embedding: Transformed Embedding {class: in_module}
    # p1: ⊗ {class: operator}
    # c -> p1: {style: {stroke: "#000000"; font-color: black}}
    c -> mp_block: {style: {stroke: "#000000"; font-color: black}}
    # transformed_embedding -> p1: {style: {stroke: "#000000"; font-color: black}}
    # p1 -> sum_j: {style: {stroke: "#000000"; font-color: black}}
    mp_block:  Message-Passing Blocks {
        class: in_module
        style: {stroke-dash: 3; multiple: true}
        # direction: right
        # sa: Self-attention {class: in_module}
        # mpln: Layer norm{class: in_module}
        # sa -> mpln: {style: {stroke: "#000000"; font-color: black}}
        # mpln -> sa: x number of message-passing steps {style: {stroke: "#000000"; font-color: black}}
    }
    # sum_j -> mp_block.sa: {style: {stroke: "#000000"; font-color: black}}
    # p1 -> mp_block: {style: {stroke: "#000000"; font-color: black}}
    nl_block: Nonlinear Block {
        class: in_module
        # nld1: Dense {class: in_module}
        # nld2: Dense {class: in_module}
        # nlln: Layer Norm {class: in_module}
        # nlma: Mish Activation {class: in_module}
        # nld1 -> nlln -> nlma -> nld2: {style: {stroke: "#000000"; font-color: black}}
        # nlrescon: ⊕ {class: operator}
        # nld2 -> nlrescon: {style: {stroke: "#000000"; font-color: black}}
    }
    mp_block -> nl_block: {style: {stroke: "#000000"; font-color: black}}
    # transformed_embedding -> nl_block: Residual connection {style: {stroke: "#000000"; font-color: black}}
    # mp_block.mpln -> nl_block.nld1: {style: {stroke: "#000000"; font-color: black}}
    # transformed_embedding -> nl_block.nlrescon: Residual connection {style: {stroke: "#000000"; font-color: black}}
}

# zi -> sarb_emb: {style: {stroke: "#000000"; font-color: black}}
# zj -> sarb_emb: {style: {stroke: "#000000"; font-color: black}}
# f -> ac.sum_j: {style: {stroke: "#000000"; font-color: black}} #ac.3b: TensorDense {style: {stroke: "#000000"; font-color: black}}
# f -> ac.c: {style: {stroke: "#000000"; font-color: black}}
# sarb_emb -> ac.transformed_embedding: Dense {style: {stroke: "#000000"; font-color: black}}
# ac.nl_block.nlrescon -> acf: {style: {stroke: "#000000"; font-color: black}}
ac.nl_block -> acf.equation: {style: {stroke: "#000000"; font-color: black}}

classes: {
    operator: {shape: circle
               width: 35
               height: 35
               style: {fill: "#FFFFFF"
                       stroke: "#000000"
                    #    font: mono
                      }
    }
    empty: {
            # label: ""
            width: 50
            height: 50
            style: {
                fill: transparent
                stroke: transparent
                font-size: 24
            }
    }
    sarb: {
        style: {
            fill: "#44BB99"
            stroke: "#000000"
        }
    }
    in_module: {
        style: {
            fill: "#FFFFFF"
            stroke: "#000000"
            # opacity: 0.5
        }
    }
    ac: {
        style: {
            fill: "#BBCC33"
            stroke: "#000000"
            bold: true
        }
    }
    bc: {
        style: {
            fill: "#EEDD88"
            stroke: "#000000"
        }
    }
    rd: {
        style: {
            fill: "#EE8866"
            stroke: "#000000"
        }
    }
    ro: {
        style: {
            fill: "#FFAABB"
            stroke: "#000000"
        }
    }
    outs: {
        style: {
            fill: "#DDDDDD"
            stroke: "#000000"
            multiple: true
        }
    }
    input : {
        # label: ""
        width: 50
        height: 50
        style: {
            fill: "#99DDFF"
            stroke: "#000000"
            multiple: true
        }
    }
}

vars: {
    d2-config: {
      layout-engine: elk
      pad: 10
    #   theme-id: 101
    }
}