# direction: right

vars: {
    d2-config: {
      layout-engine: elk
      pad: 10
    #   theme-id: 101
    }
}

acfi: {
    label: ""
    class: empty
    equation: |latex
        \huge{\mathbf{x}_i^{\mathrm{AC}}}
    |
}
acfj: {
    label: ""
    class: empty
    equation: |latex
        \huge{\mathbf{x}_j^{\mathrm{AC}}}
    |
}

r: {label: ""
    equation: |latex
        \huge{\mathbf{r}_{ij}}
    |
    class: empty}
bcf: {
    label: ""
    class: empty
    equation: |latex
        \huge{\mathbf{x}_{ij}^{\mathrm{BC}}}
    |
}

bc: Bond-Centered Descriptor {
    class: bc
    s1: ⊕ {class: operator}
    d1: Dense {class: in_module}
    ln: Layer Norm {class: in_module}
    mish: mish Activation {class: in_module}
    d2: Dense {class: in_module}
    s1 -> d1 -> ln -> mish -> d2: {style: {stroke: "#000000"; font-color: black}}
    s2: ⊕ {class: operator}
    d1 -> s2: {style: {stroke: "#000000"; font-color: black}}
    d2 -> s2: {style: {stroke: "#000000"; font-color: black}}
    bond_exp: Basis\nExpansion {class: in_module}
    d3be: Dense {class: in_module}
    bond_exp -> d3be: {style: {stroke: "#000000"; font-color: black}}
    tm: Tensor Product {class: in_module}
    s2 -> tm: {style: {stroke: "#000000"; font-color: black}}
    d3be -> tm: {style: {stroke: "#000000"; font-color: black}}
}
acfi.equation -> bc.s1: {style: {stroke: "#000000"; font-color: black}}
acfj.equation -> bc.s1: {style: {stroke: "#000000"; font-color: black}}
r.equation -> bc.bond_exp: {style: {stroke: "#000000"; font-color: black}}
bc.tm -> bcf.equation: {style: {stroke: "#000000"; font-color: black}}

classes: {
    operator: {shape: circle
               width: 35
               height: 35
               style: {fill: "#FFFFFF"
                       stroke: "#000000"
                       font-size: 24
                      }
    }
    empty: {
            width: 50
            height: 50
            style: {
                fill: transparent
                stroke: transparent
                font-size: 24
            }
    }
    sarb: {
        style: {
            fill: "#44BB99"
            stroke: "#000000"
            font-size: 24
        }
    }
    in_module: {
        style: {
            fill: "#FFFFFF"
            stroke: "#000000"
            font-size: 24
        }
    }
    ac: {
        style: {
            fill: "#BBCC33"
            stroke: "#000000"
            font-size: 24
        }
    }
    bc: {
        style: {
            fill: "#EEDD88"
            stroke: "#000000"
            bold: true
            font-size: 28
        }
    }
    rd: {
        style: {
            fill: "#EE8866"
            stroke: "#000000"
        }
    }
    ro: {
        style: {
            fill: "#FFAABB"
            stroke: "#000000"
        }
    }
    outs: {
        style: {
            fill: "#DDDDDD"
            stroke: "#000000"
            multiple: true
        }
    }
    input : {
        width: 50
        height: 50
        style: {
            fill: "#99DDFF"
            stroke: "#000000"
            multiple: true
        }
    }
}
