n_epochs: 50
callbacks: 
- name: csv

data:
  directory: models
  experiment: slh
  data_path: <PATH>
  n_train: 100
  n_valid: 10
  bond_fraction : 1.0
  batch_size: 2
  valid_batch_size: 2
  shuffle_buffer_size: 100
  energy_unit: eV
  pos_unit: Ang

model:
  atom_centered:
    descriptor: 
      descriptor_name: SAAtomCenteredDescriptor
      use_fused_tensor: False
      embedding_residual_connection: True
      mp_steps: 2
      mp_degree: 4
      mp_options: {}
    radial_basis:
      cutoff: <CUTOFF>
      num_radial: 8
      max_degree: 2
      num_elemental_embedding: 8
      tensor_module: tensor
      tensor_module_dtype: float32
  bond_centered:
    cutoff: <CUTOFF>
    max_basis_degree: 2
    max_degree: 4
    max_actp_degree: 4
    tensor_module: tensor
    tensor_module_dtype: float32
  mlp:
    mlp_layer_widths: [128]
    mlp_dtype: float32
    mlp_activation_function: shifted_softplus

optimizer:
  name: "adam"
  lr: 0.001
  opt_kwargs: {nesterov: True}
  schedule:
    name: exponential_decay
    decay_rate: 0.99
    end_value: 0.0001
    transition_begin: 20
    transition_steps: 1

loss:
  name: weighted_mse_and_rmse
  loss_parameters:
    off_diagonal_weight: 4.0
    on_diagonal_weight : 1.0
    mse_weight         : 1.0
    rmse_weight        : 1.0
    loss_multiplier    : 5.0

patience: null
seed: 2465
